// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcTVfwQxpPFQi7C20L-gz9wN0iPXkO4pc',
    appId: '1:183063642676:web:5636577f3a298afe3c0061',
    messagingSenderId: '183063642676',
    projectId: 'trip-auth-a7bc3',
    authDomain: 'trip-auth-a7bc3.firebaseapp.com',
    storageBucket: 'trip-auth-a7bc3.firebasestorage.app',
    measurementId: 'G-KK5PFQT4PT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAaXsxdcMdJ6k0iqqbEK6yrOEDF4Irn3Q',
    appId: '1:183063642676:android:b1089d3885015d383c0061',
    messagingSenderId: '183063642676',
    projectId: 'trip-auth-a7bc3',
    storageBucket: 'trip-auth-a7bc3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXRTJUT4R1TKqj0Z48S6vW9_Xx61rCelw',
    appId: '1:183063642676:ios:14e73d6f4ca147253c0061',
    messagingSenderId: '183063642676',
    projectId: 'trip-auth-a7bc3',
    storageBucket: 'trip-auth-a7bc3.firebasestorage.app',
    iosBundleId: 'com.example.triptale',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXRTJUT4R1TKqj0Z48S6vW9_Xx61rCelw',
    appId: '1:183063642676:ios:14e73d6f4ca147253c0061',
    messagingSenderId: '183063642676',
    projectId: 'trip-auth-a7bc3',
    storageBucket: 'trip-auth-a7bc3.firebasestorage.app',
    iosBundleId: 'com.example.triptale',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCcTVfwQxpPFQi7C20L-gz9wN0iPXkO4pc',
    appId: '1:183063642676:web:8a0317542af3aa8a3c0061',
    messagingSenderId: '183063642676',
    projectId: 'trip-auth-a7bc3',
    authDomain: 'trip-auth-a7bc3.firebaseapp.com',
    storageBucket: 'trip-auth-a7bc3.firebasestorage.app',
    measurementId: 'G-49HFVXP9EJ',
  );
}
